### ISSUE TITLE
Error: processing response error

### ISSUE THREAD

**Issue by Matarwy** [dmihal/eth-permit#18]
ethers version: 5.5.1
nodejs version: 16
`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32601,\"message\":\"the method eth_signTypedData_v4 does not exist/is not available\"}}", error={"code":-32601}, requestBody="{\"method\":\"eth_signTypedData_v4\",\"params\":[\"0xBaA081282D82602d79EF300Ba29EC3b2466D4723\",\"{\\\"types\\\":{\\\"EIP712Domain\\\":[{\\\"name\\\":\\\"name\\\",\\\"type\\\":\\\"string\\\"},{\\\"name\\\":\\\"version\\\",\\\"type\\\":\\\"string\\\"},{\\\"name\\\":\\\"chainId\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"verifyingContract\\\",\\\"type\\\":\\\"address\\\"}],\\\"Permit\\\":[{\\\"name\\\":\\\"holder\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"spender\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"nonce\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"expiry\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"allowed\\\",\\\"type\\\":\\\"bool\\\"}]},\\\"primaryType\\\":\\\"Permit\\\",\\\"domain\\\":{\\\"name\\\":\\\"Dai Stablecoin\\\",\\\"version\\\":\\\"1\\\",\\\"chainId\\\":\\\"0x1\\\",\\\"verifyingContract\\\":\\\"0x6b175474e89094c44da98b954eedeac495271d0f\\\"},\\\"message\\\":{\\\"holder\\\":\\\"0xBaA081282D82602d79EF300Ba29EC3b2466D4723\\\",\\\"spender\\\":\\\"0x5049bE34eE05627aD0C500f11B25d23c02F530b1\\\",\\\"nonce\\\":\\\"0x0000000000000000000000000000000000000000000000000000000000000000\\\",\\\"expiry\\\":\\\"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\\\",\\\"allowed\\\":true}}\"],\"id\":49,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://eth.llamarpc.com", code=SERVER_ERROR, version=web/5.7.1)
    at _Logger.makeError (index.ts:269:28)
    at _Logger.throwError (index.ts:281:20)
    at index.ts:341:28
    at Generator.next (<anonymous>)
    at fulfilled (browser-geturl.ts:55:2)
![Screenshot 2023-09-04 020904](https://github.com/dmihal/eth-permit/assets/67296782/ca107808-e056-4b81-a4e8-876ef5cb541a)
`

**Comment by Enflow-io** [comment]
+1
